name: scorecard
on:
  schedule: [{cron: "0 6 * * 1"}]
  push: {branches: [main]}
permissions: {contents: read, security-events: write}

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c890d416ceef5c5ac4bbc71393b68ea3eb690c # v5.0.2
      - uses: actions/setup-python@e797f83af5d1bb601b85b8e2370926db8c02ac00 # v5.0.0
        with: {python-version: "3.12"}
      - uses: ossf/scorecard-action@ec7f4a3d0f0f8348f9ed0920274f1a6382d74eea # v2.4.0
        with:
          results_format: sarif
          results_file: results.sarif
          publish_results: true
      - uses: github/codeql-action/upload-sarif@ec7f4a3d0f0f8348f9ed0920274f1a6382d74eea # v3.28.0
        with: {sarif_file: results.sarif}
